### ISSUE TITLE
Issues with the documentation

### ISSUE THREAD

**Issue by Zanndorin** [Trousseau-io/docs.trousseau.io#1]
Hi, So I have been trying to follow your guide and noticed that there are a lot of typoes that make the script not work (at least I hope that is the issue. Otherwise I have been doing some things really wrong
This is an example from the daemonset 

```
volumeMounts:
            - name: vault-kms
              mountPath: /opt/trousseau-kms
            - name: shared-data
              mountPath: /opt/trousseau/
      volumes:
        - name: trousseau-kms
          hostPath:
            path: /opt/trousseau-kms
```

I assume that the volumeMounts name should be trousseau-kms in this case.

Any way I am trying to get this to work on our RKE2 cluster but I get stuck on the fact that the trousseau-kms-provider container gets the following error:

```
caller":"kubernetes-kms-vault/main.go:90","msg":"listen unix /opt/trousseau-kms/vaultkms.socket: bind: permission denied\n","stacktrace":"main.main\n\t/work/cmd/kubernetes-kms-vault/main.go:90\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

I have played around with some other variables and finding other typo'es in the documentation/code but I am a bit lost on what to do here and would appreciate some help.

 image: ghcr.io/ondat/trousseau:v1.1.3 
 Vault v1.14.1
